### ISSUE TITLE
load layer - Wetlands 

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/mdba-hub#1]
https://data.gov.au/dataset/wetlands-gis-of-the-murray-darling-basin-series-2-0

**Comment by M-Nicholls** [comment]
having trouble loading this one - keeps throwing an error when I check it in spatial-dev

**Comment by adam-collins** [comment]
The imported shapefile has null groupname records.

It is working after this correction.

```
update objects set id = '' where id is null and fid = 'cl3002';
update objects set name = '' where name is null and fid = 'cl3002';
update objects set "desc" = '' where "desc" is null and fid = 'cl3002';
update "3002" set groupname = '' where groupname is null;
```

layers/ready/shape/wetlands_mdb_2.shp is refreshed with pgsql2shp and the updated table "3002".

**Comment by ansell** [comment]
Duplicate issue, closing in favour of https://github.com/AtlasOfLivingAustralia/layers-service/issues/54
