### ISSUE TITLE
bioCollect hub - develop new skin to apply styles from the ALA-MDBA hub

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/mdba-hub#10]
Develop and apply a new skin which is consistent with styling of the ALA-MDBA hub

**Comment by temi** [comment]
https://upsource.ala.org.au/mdba-hub/review/MH-CR-1
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-135
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-50
