### ISSUE TITLE
Allow hub filter based on spatial constraint

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/mdba-hub#18]
Add the Murray-Darling Basin boundary layer to the fieldcapture facet selection options. 

Also include other layers available in the Regions tool which are not yet available to fieldcapture facet selection. This must also include the following layers:
- MDBA boundary layer
- MDBA sub-catchments - needs to be indexed to allow select and filter by sub-catchment
- Traditional owner groups as provided by MDBA
- Other layers requested by MDBA

**Comment by chrisala** [comment]
Organisation name facet is acceptable.

**Comment by temi** [comment]
also in search result page's map, add these layers as overlays.

**Comment by temi** [comment]
@pbrenton is this issue for basin champions (biocollect) or mdba-hub?
