### ISSUE TITLE
Load Layer - Basin valleys

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/mdba-hub#19]
http://kid.rivers.prod.local/bpkid-view-internal.php?asset=2501  or provided file

**Comment by M-Nicholls** [comment]
alternative link
http://www.mdba.gov.au/kid/kid-view.php?key=rPW470/etQtCEjb9cJT5cCpTXE*Ec0PzTV202*FpruM=

**Comment by ansell** [comment]
Duplicate issue, closing this in favour of https://github.com/AtlasOfLivingAustralia/layers-service/issues/48
