### ISSUE TITLE
Default views of data should always be data / data sets from MDBA datasets only

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/mdba-hub#37]
Set default views to just MDBA data and datasets and allow toggle to view all occurrence records or datasets with occurrence records falling within the MDBA boundary.

**Comment by ansell** [comment]
Refers to issue #6

**Comment by temi** [comment]
Ensure this happens in 
- browse by catchment
- browse by dataset
- traditional owner groups
- quick search

**Comment by temi** [comment]
all tasks on this is done on different issues
