### ISSUE TITLE
Search by Catchment - Link page from home page button

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/mdba-hub#42]
"Search by Catchment" needs to link to a page like http://regions.ala.org.au/#rt=Major+drainage+divisions&region=DARLING+RIVER, but respecting the following adjustments:
- hard-set a default geographic constraint to the MDBA boundary layer and zoom to extent
- MDBA boundary layer to act as a mask for data points and datasets
- remove the marine regions facet and any irrelevant layers from the "Other regions" facet
- Provide a toggle view option to display MDBA data (default) and all data

**Comment by chrisala** [comment]
An MDBA skinned version of regions with customised facets and default selection should suffice to begin with.  (and a link back to the mdba-hub to view records).

**Comment by pbrenton** [comment]
Use the SRA valleys layer as the sub-set to explore regions.
