### ISSUE TITLE
"Search by Datasets" - New page behind home page button

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/mdba-hub#43]
"Search by Dataset" needs to link to a page like http://collections.ala.org.au/datasets, but respecting the following adjustments:
- hard-set a default geographic constraint to datasets with data points occurring within the MDBA boundary layer
- MDBA boundary layer to act as a mask for data points and datasets
- Provide a toggle view option to display MDBA datasets (default) and all datasets
- Retain
  
  search, sort and facet filter features from the ALA datasets page

**Comment by chrisala** [comment]
Produce a page similar to the collectory from the biocache search results / facets.
