### ISSUE TITLE
Add access control for MDBA hub admins

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/mdba-hub#44]
Create a new role in CAS for MDBA_ADMIN

This role needs edit access to edit content on all static pages in the hub as well as the content in the "Resources" page

**Comment by ansell** [comment]
Are CAS roles integrated with GitHub? The static pages on the hub seem to be implemented as GSP pages here, not as a wordpress/blog style although I may be missing something there.

**Comment by chrisala** [comment]
The role has been added. Checking the role before editing content or resources will be included as a part of those tasks.
