### ISSUE TITLE
Add "Resources" page behind the resources home page button

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/mdba-hub#45]
Link the "Resources" button on the home page to a new page which resembles the resources tab in BioCollect projects.

Adding, editing and removing attached resources should be actioned from an on-page edit button available only to MDBA_ADMIN and ALA_ADMIN users.

**Comment by chrisala** [comment]
Extracted the preview code into the document-preview-plugin.
Copied and modified biocollect document list and view code:
https://upsource.ala.org.au/mdba-hub/review/MH-CR-2
This change requires updates to your local configuration.
It also depends on updates to ecodata in test.
