### ISSUE TITLE
Load data set: MDBA phytoplankton data

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/mdba-hub#46]
Please load the attached set of files with MDBA phytoplankton point data.

[MDBA phytoplankton data.zip](https://github.com/AtlasOfLivingAustralia/mdba-hub/files/203948/MDBA.phytoplankton.data.zip)

**Comment by ansell** [comment]
This zip file has 9 XLSX files inside of it. It is likely to be very messy but will see how it goes.

**Comment by ansell** [comment]
Useful documentation for this:

http://www.mdba.gov.au/sites/default/files/pubs/River-Murray-Phytoplankton-Monitoring-Program-review-2015.docx

**Comment by ansell** [comment]
More useful documentation for the early datasets:

http://www.mdba.gov.au/sites/default/files/pubs/Revision-of-the-River-Murray-WQ-Monitoring-Program.docx

**Comment by ansell** [comment]
More useful documentation:

http://www.clw.csiro.au/publications/waterforahealthycountry/2009/wfhc-Flow-Regimes-MDB.pdf

**Comment by ansell** [comment]
Many of the algae species/families/orders that are referenced in this dataset are not yet recognised, but more should be recognised during a reprocessing after the new name matching algorithm is published, based on manually checking them at the dev version:

http://bie-dev.ala.org.au/ala-name-explorer/

**Comment by ansell** [comment]
Data resource created to contain this dataset:

http://collections.ala.org.au/public/show/dr4766

**Comment by ansell** [comment]
Load of this scheduled into jenkins, but cannot index them during the week due to the use of ala-rufus as the live production index. Will need to wait for Monday/next week to be able to search for the records.

**Comment by ansell** [comment]
In the meantime, the dataset can be viewed in the Sandbox at:

http://sandbox.ala.org.au/datacheck/dataCheck/redirectToSpatialPortal?uid=drt8594

http://sandbox.ala.org.au/datacheck/dataCheck/redirectToBiocache?uid=drt8594
