### ISSUE TITLE
Update the layers displayed on the mdba regions app and set the default to the MDBA boundary region

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/mdba-hub#50]

**Comment by pbrenton** [comment]
For the "browse by catchments" landing page on the regions app the default layer needs to be the SRA valleys layer (cl3003), with all records falling outside the basin boundary (cl2110) to be masked out of the returned data points. Also set the default zoom level to display only the MDBA region at the largest possible scale and centered appropriately within the map panel.

Until use of the required/appropriate spatial layer is approved we have been asked to use the SRA valleys layer (cl3003) for the "Browse by Indigenous owner groups" button. This will be swapped out when the actual layer has been approved for use. 

Please also use the cl2110 layer to mask out data points falling outside the MDBA region boundary for all faceted map views.

Adjustments required to the regions facet list, including display sequence change:
-   States and territories - retain - list sequence 4
-   Local government - retain - list sequence 5
-   Biogeographic regions - retain - list sequence 9
-   Marine regions - remove 
-   Management regions - retain - list sequence 6
-   Indigenous protected areas - retain - list sequence 7
-   Indigenous land use agreements - retain - list sequence 8
-   Major drainage divisions  - replace with cl3003 using title "Murray-Darling basin sub-catchments"  - list sequence 1  
-   Bush Heritage Reserves - remove 
-   Other regions - remove all except the following and elevate these to same level as above
    Collaborative Australian Protected Areas Database - retain - list sequence 10
    Directory of important wetlands - retain - list sequence 2
    RAMSAR wetland regions - retain - list sequence 3

**Comment by ansell** [comment]
6 layers on spatial-test waiting to be pulled/pushed into the production server. Doesn't looks like the acid sulphate soils layer will make it during this sprint, but I now know the basic process to do that one quickly (assuming no more bugs) when MDBA provide it in future.

**Comment by ansell** [comment]
All of the data resources are linked to the mdba data hub id:

http://collections.ala.org.au/dataHub/show/dh10
