### ISSUE TITLE
Regions page - apply MDBA regional boundary as a mask for all regional layers

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/mdba-hub#66]
Need to apply the MDBA region boundary as a mask for all regions layers. Also zoom to max possible scale for the map and center on the MDBA region. - maybe even increase the height of the map to maximise the region display.

When masking, show all shapes in full which intersect with or are fully contained within the MDBA region boundary area. Exclude all others.

**Comment by temi** [comment]
@pbrenton This job is very time consuming. can we put it on hold?

**Comment by pbrenton** [comment]
Hi Temi,

I’ll confer with Katrina next week, but my gut feeling is that this will be important to them, if not in the short term, at least in the medium term.

If it is preventing you from steaming ahead with progress on other tickets, I think parking it for now is OK though.

Thanks

Peter B.

**Comment by pbrenton** [comment]
Probably also associated with #88
