### ISSUE TITLE
Change "Browse by Traditional Owner Group" to "Browse by Wetland"

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/mdba-hub#67]
MDBA have not been able to obtain required approvals to use the Indigenous owners area maps and therefore need to change the link on the home page. They have decided to use the regional wetlands as the default filter on the regions map view, linking from the bottom left button on the home page. 

Please change button on the home page, landing page and default filter.

**Comment by ansell** [comment]
Which of the spatial layers is to be used for the regional wetlands? The names given in Wetlands GIS are not comprehensive and are very sparse across the basin. The distribution is as below:

![wetlands-name](https://cloud.githubusercontent.com/assets/82365/14698546/516e1c2a-07d3-11e6-9e25-6639ddeb20b1.png)

Would it be acceptable to use the valley names that fully cover the basin (see below):

![mdb_sra_valleys](https://cloud.githubusercontent.com/assets/82365/14698685/8d4d327a-07d4-11e6-8a72-6d9d745d2305.png)

**Comment by pbrenton** [comment]
Hi Peter,

Please use the “Directory of important wetlands” layer, but it needs to be masked with the MDBA region boundary layer to exclude all wetlands which fall completely outside that boundary.

Thanks

Peter B.

**Comment by ansell** [comment]
The layer id for this is:

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl901

**Comment by sat01a** [comment]
Browse by Wetland will now point to cl901(h#rt=Directory+of+Important+Wetlands)
(Updated ala-inventory and ala-install script.)

https://upsource.ala.org.au/mdba-hub/review/MH-CR-6

**Comment by pbrenton** [comment]
This issue has been reactivated because MDBA now have permission to use the required context layer for this view. They are seeking to obtain a shape file of the layer so that we can load it. In the absence of this though they have requested that we use the MDBA Water Resource Plan map as the contextual layer. Confirmation to be provided soon.
