### ISSUE TITLE
Login link points to unavailable page

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/mdba-hub#93]
The Login link on the mdba-hub website points to:

https://auth.ala.org.au/cas/login/login?service=http://mdba.ala.org.au/

instead of:

https://auth.ala.org.au/cas/login?service=http://mdba.ala.org.au/

**Comment by patkyn** [comment]
Fixed config in mdba prod. Need to test the script

**Comment by ansell** [comment]
Working
